## Nexys 4 rev B - integracion posicion, botones y display
## Reloj de 100 MHz
set_property PACKAGE_PIN E3 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -add -name sys_clk_pin -period 10.000 -waveform {0 5} [get_ports clk]
## Reset manual central BTNC
set_property PACKAGE_PIN E16 [get_ports btnC]
set_property IOSTANDARD LVCMOS33 [get_ports btnC]
## Posicion Q0-Q2 desde protoboard por JA1-JA3
set_property PACKAGE_PIN B13 [get_ports {position_async[0]}]
set_property PACKAGE_PIN F14 [get_ports {position_async[1]}]
set_property PACKAGE_PIN D17 [get_ports {position_async[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {position_async[*]}]
## Ocho botones externos por Pmod JB
set_property PACKAGE_PIN G14 [get_ports {buttons_async[0]}]
set_property PACKAGE_PIN P15 [get_ports {buttons_async[1]}]
set_property PACKAGE_PIN V11 [get_ports {buttons_async[2]}]
set_property PACKAGE_PIN V15 [get_ports {buttons_async[3]}]
set_property PACKAGE_PIN K16 [get_ports {buttons_async[4]}]
set_property PACKAGE_PIN R16 [get_ports {buttons_async[5]}]
set_property PACKAGE_PIN T9  [get_ports {buttons_async[6]}]
set_property PACKAGE_PIN U11 [get_ports {buttons_async[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {buttons_async[*]}]
## LEDs LD0-LD7 muestran la posicion activa
set_property PACKAGE_PIN T8 [get_ports {led[0]}]
set_property PACKAGE_PIN V9 [get_ports {led[1]}]
set_property PACKAGE_PIN R8 [get_ports {led[2]}]
set_property PACKAGE_PIN T6 [get_ports {led[3]}]
set_property PACKAGE_PIN T5 [get_ports {led[4]}]
set_property PACKAGE_PIN T4 [get_ports {led[5]}]
set_property PACKAGE_PIN U7 [get_ports {led[6]}]
set_property PACKAGE_PIN U6 [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[*]}]
## Segmentos A-G y punto decimal
set_property PACKAGE_PIN L3 [get_ports {seg[0]}]
set_property PACKAGE_PIN N1 [get_ports {seg[1]}]
set_property PACKAGE_PIN L5 [get_ports {seg[2]}]
set_property PACKAGE_PIN L4 [get_ports {seg[3]}]
set_property PACKAGE_PIN K3 [get_ports {seg[4]}]
set_property PACKAGE_PIN M2 [get_ports {seg[5]}]
set_property PACKAGE_PIN L6 [get_ports {seg[6]}]
set_property PACKAGE_PIN M4 [get_ports dp]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports dp]
## Anodos AN0-AN7; solo AN0-AN3 se usan, los demas permanecen apagados
set_property PACKAGE_PIN N6 [get_ports {an[0]}]
set_property PACKAGE_PIN M6 [get_ports {an[1]}]
set_property PACKAGE_PIN M3 [get_ports {an[2]}]
set_property PACKAGE_PIN N5 [get_ports {an[3]}]
set_property PACKAGE_PIN N2 [get_ports {an[4]}]
set_property PACKAGE_PIN N4 [get_ports {an[5]}]
set_property PACKAGE_PIN L1 [get_ports {an[6]}]
set_property PACKAGE_PIN M1 [get_ports {an[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[*]}]